### ISSUE TITLE
Guard deprecation warning from guard-rack code

### ISSUE THREAD

**Issue by elado** [dblock/guard-rack#15]
```
    ******** BIG DEPRECATION WARNING !! ********

    Hi, Guard here.

    You're including lib/guard/guard.rb ...

    ... which contains code deprecated over a year ago!


    This file will likely be removed in the next version, so make sure you're
    not requiring it anywhere to ensure safe gem upgrades.

    If this message is annoying and you can't quickly fix the issue (see below),
    you have 2 options:

      1) Simply set the env variable "GUARD_GEM_SILENCE_DEPRECATIONS" to "1" to
      skip this message

      2) Freeze the gem to a previous version (not recommended because upgrades
      are cool and you might forget to unfreeze later!).

      E.g. in your Gemfile:

        if Time.now > Time.new(2014,11,10)
          gem 'guard', '~> 2.8'
        else
          # Freeze until 2014-11-10 - in case we forget to change back ;)
          gem 'guard', '= 2.7.3'
        end

    If you don't know which gem or plugin is requiring this file, here's a
    backtrace:

    gems/2.1.0/gems/guard-2.8.1/lib/guard/guard.rb:45:in `<module:Guard>'
	 >> gems/2.1.0/gems/guard-2.8.1/lib/guard/guard.rb:3:in `<top (required)>'
	 >> gems/2.1.0/gems/guard-rack-1.4.0/lib/guard/rack.rb:2:in `require'
	 >> gems/2.1.0/gems/guard-rack-1.4.0/lib/guard/rack.rb:2:in `<top (required)>'
	 >> gems/2.1.0/gems/guard-rack-1.4.0/lib/guard-rack.rb:1:in `require'"
```

**Comment by michaelherold** [comment]
This was fixed with the release of 2.0.0. Closing.
