### ISSUE TITLE
Undefined method “shutdown”

### ISSUE THREAD

**Issue by FranklinYu** [dblock/guard-rack#27]
When I run Guard with `-i`/`--no-interactions` and then shutdown with Ctrl-C, following stack trace occurs:

```traceback
Traceback (most recent call last):
	5: from /Users/franklinyu/.gem/ruby/2.5.5/gems/sinatra-2.0.5/lib/sinatra/main.rb:26:in `block in <module:Sinatra>'
	4: from (eval):1:in `run?'
	3: from /Users/franklinyu/.gem/ruby/2.5.5/gems/sinatra-2.0.5/lib/sinatra/main.rb:11:in `block in <class:Application>'
	2: from /Users/franklinyu/.gem/ruby/2.5.5/gems/sinatra-2.0.5/lib/sinatra/base.rb:1237:in `block in set'
	1: from /Users/franklinyu/.gem/ruby/2.5.5/gems/rack-2.0.6/lib/rack/server.rb:291:in `block in start'
/Users/franklinyu/.gem/ruby/2.5.5/gems/rack-2.0.6/lib/rack/handler/webrick.rb:48:in `shutdown': undefined method `shutdown' for nil:NilClass (NoMethodError)
```

Note that the process still exits. I’m just curious whether I should to worry about it.

**Comment by dblock** [comment]
Looks like a bug.
